# create a dev conda environment with: `make create_env` or `conda env create -f environment_py39.yml`
name: pycgm310
channels:
- conda-forge
- opensim-org
- default

dependencies:
- python==3.10
- opensim=4.4=py310np121
- btk
- scipy
- matplotlib
- pandas
- enum34
- configparser
- pytest
- pytest-mpl
- scikit-learn
- beautifulsoup4 
- pyyaml
- yamlordereddictloader
- xlrd
- openpyxl
- xlwt
- lxml
- pip


