package:
  name: "pycgm2"
  version: "4.3rc3"

about:

  summary: "the python Conventional Gait Model Library"
  home: https://github.com/pyCGM2/pyCGM2
  maintainer: Fabien LEBOEUF <fabien.leboeuf@chu-nantes.com>
  licence: CC-BY-SA-4.0


requirements:
  
  build:
    - python={{ python_version }} 
    - setuptools
    - pip
    - numpy
    

  run:
    - python={{ python_version }}
    - pip
    - btk
    - {% if python_version == '3.7'%}
      opensim
      {% endif %}
    - scipy
    - matplotlib
    - pandas
    - enum34
    - configparser
    - pytest
    - pytest-mpl
    - scikit-learn
    - beautifulsoup4 
    - pyyaml
    - yamlordereddictloader
    - xlrd
    - openpyxl
    - xlwt
    - lxml
    - myst-parser
    - sphinx
    - sphinx-argparse
    - sphinxcontrib-mermaid
    - pydata-sphinx-theme

channels:
  - conda-forge
  - opensim-org



source:
  path: ..

build:
  script: pip install .
  string: py{{ python_version | replace(".", "") }}
  #post-link: scripts/post-link.bat

test:
  imports:
    - name: pyCGM2
      optional: false


target_platform:
  - win-64
