name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.7
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - sphinx == 4.5.0
    - myst-parser == 0.17.2
    - sphinx-rtd-theme == 1.0.0
    - sphinxcontrib-mermaid == 0.7.1
    - numpy==1.18.5
    - scipy==1.5.4
    - matplotlib==3.3.3
    - pandas ==1.1.4
    - enum34==1.1.10
    - configparser==5.0.1
    - beautifulsoup4==4.9.3
    - pyyaml==5.3.1
    - yamlordereddictloader==0.4.0
    - xlrd==1.2.0
    - lxml==4.6.1
    - openpyxl==3.0.5
    - xlwt==1.3.0
    - pytest==6.1.2
    - pytest-mpl==0.12
    - pathlib2==2.3.5
    - sphinx-argparse==0.3.1
    - scikit-learn== 0.23.2
