name: docs
channels:
- conda-forge
- opensim-org
- default
dependencies:
- python==3.7
- opensim=4.4=py37np120
#- btk
- scipy
- matplotlib
- pandas
- enum34
- configparser
- pytest
- pytest-mpl
- scikit-learn
- beautifulsoup4 
- pyyaml
- yamlordereddictloader
- xlrd
- openpyxl
- xlwt
- lxml
- pip
